services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dictionary

volumes:
  mysql: