services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - "83:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    environment:
     MYSQL_DATABASE: dictionary
     MYSQL_ROOT_PASSWORD: password

volumes:
  mysql: